name: Update README

on:
  schedule:
    - cron: '*/30 * * * *' # Update every 30 minutes
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Update Profile README

    steps:
      - uses: actions/checkout@v3
      #
      # "{version}" is a placeholder and should be replaced with the latest release of recent-activity
      - uses: iamgojoof6eyes/github-activity-readme@patch-1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
